"""
Base Processor class.

The Processor interface/base class states all the functions needed to be implemented.
Each child processor class must implement the methods. Each child contains specific
functionality. For this case one child class should be enough, but this structure
allows possible changes in the future.
"""
from abc import ABC, abstractmethod
from typing import List, Dict, Optional
import logging
from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class ProcessingStatus(Enum):
    """Status of document processing."""
    PENDING = "pending"
    PROCESSED = "processed"
    FAILED = "failed"


@dataclass
class ProcessedChunk:
    """Represents a processed document chunk with its content and metadata."""
    
    # Document identification
    document_id: Optional[str] = None
    chunk_id: Optional[str] = None
    source_document_path: str = ""
    source_type: str = ""
    
    # Content
    content: str = ""
    content_type: str = "text/markdown"
    
    # Chunk information
    chunk_index: int = 0
    total_chunks: int = 1
    
    # Metadata
    processed_at: Optional[datetime] = None
    status: ProcessingStatus = ProcessingStatus.PENDING
    
    # Additional metadata
    metadata: Dict = None
    
    # Vector embedding (would be generated by storer)
    embedding: Optional[List[float]] = None
    
    def __post_init__(self):
        """Initialize default values."""
        if self.metadata is None:
            self.metadata = {}
        if self.processed_at is None:
            self.processed_at = datetime.now()


class Processor(ABC):
    """
    Abstract base class for all processors.
    
    The Processor reads the stored raw documents, uses docling to convert to docling document.
    Adds additional processing, for now only export to markdown. Finally chunks the markdown
    and creates metadata. The processor uses sqlalchemy to store the chunks and their metadata.
    """
    
    def __init__(self, config: Dict, db_session):
        """
        Initialize the processor.
        
        Args:
            config: Configuration dictionary for the processor
            db_session: SQLAlchemy database session for storing chunks and metadata
        """
        self.config = config
        self.db_session = db_session
        self.logger = logging.getLogger(__name__)
        
        # Configure logging
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )
    
    @abstractmethod
    def process(self, collected_documents: List[Dict]) -> List[ProcessedChunk]:
        """
        Process collected documents into chunks with metadata.
        
        Args:
            collected_documents: List of collected document data from collector
            
        Returns:
            List of ProcessedChunk objects containing chunked content and metadata
        """
        pass
    
    def store_processed_chunks(self, processed_chunks: List[ProcessedChunk]) -> None:
        """
        Store processed chunks and metadata in the database.
        
        Args:
            processed_chunks: List of processed chunks to store
        """
        try:
            # This would be implemented with actual SQLAlchemy code
            # For now, we'll just log the action
            for chunk in processed_chunks:
                self.logger.info(
                    f"Storing processed chunk: document={chunk.source_document_path}, "
                    f"chunk_id={chunk.chunk_id}, status={chunk.status.value}"
                )
            
            # TODO: Implement actual database storage using SQLAlchemy
            # Example:
            # for chunk in processed_chunks:
            #     db_chunk = DocumentChunk(
            #         document_id=chunk.document_id,
            #         chunk_id=chunk.chunk_id,
            #         content=chunk.content,
            #         metadata=chunk.metadata,
            #         status=chunk.status.value,
            #         processed_at=chunk.processed_at
            #     )
            #     self.db_session.add(db_chunk)
            # self.db_session.commit()
        except Exception as e:
            self.logger.error(f"Error storing processed chunks: {str(e)}")
            raise
    
    def validate_collected_document(self, collected_document: Dict) -> bool:
        """
        Validate that a collected document can be processed.
        
        Args:
            collected_document: Collected document data to validate
            
        Returns:
            True if the document is valid for processing, False otherwise
        """
        try:
            # Basic validation - can be extended by child classes
            required_fields = ['path', 'source_type', 'raw_content', 'status']
            for field in required_fields:
                if field not in collected_document:
                    self.logger.warning(f"Collected document missing required field: {field}")
                    return False
            
            # Check that content is not empty
            if not collected_document['raw_content']:
                self.logger.warning(f"Document has no content: {collected_document['path']}")
                return False
            
            # Check that collection was successful
            if collected_document['status'] != 'collected':
                self.logger.warning(f"Document was not successfully collected: {collected_document['path']}")
                return False
            
            return True
            
        except Exception as e:
            self.logger.error(f"Error validating collected document: {str(e)}")
            return False
    
    def create_processed_chunk(self, collected_document: Dict, chunk_content: str, 
                               chunk_index: int, total_chunks: int, 
                               content_type: str = "text/markdown", 
                               metadata: Dict = None) -> ProcessedChunk:
        """
        Create a ProcessedChunk object from collected document and chunk content.
        
        Args:
            collected_document: Original collected document data
            chunk_content: Content of this chunk
            chunk_index: Index of this chunk
            total_chunks: Total number of chunks
            content_type: Content type of the chunk
            metadata: Additional metadata
            
        Returns:
            ProcessedChunk object
        """
        if metadata is None:
            metadata = {}
        
        # Add basic metadata from collected document
        chunk_metadata = {
            'source_path': collected_document['path'],
            'source_type': collected_document['source_type'],
            'content_type': collected_document.get('content_type', 'unknown'),
            'original_size': len(collected_document['raw_content']),
            'chunk_size': len(chunk_content.encode('utf-8')),
            **metadata
        }
        
        return ProcessedChunk(
            source_document_path=collected_document['path'],
            source_type=collected_document['source_type'],
            content=chunk_content,
            content_type=content_type,
            chunk_index=chunk_index,
            total_chunks=total_chunks,
            status=ProcessingStatus.PROCESSED,
            metadata=chunk_metadata
        )